/* eslint-disable */
// AUTO-GENERATED by scripts/gen-flipbook.mjs — DO NOT EDIT.
export interface FlipPage { src: string; }
export const magazine = {
  width: 1000,
  height: 1414,
  pages: [
  { src: "/media/graphic_design/magazine/page-001.jpg" },
  { src: "/media/graphic_design/magazine/page-002.jpg" },
  { src: "/media/graphic_design/magazine/page-003.jpg" },
  { src: "/media/graphic_design/magazine/page-004.jpg" },
  { src: "/media/graphic_design/magazine/page-005.jpg" },
  { src: "/media/graphic_design/magazine/page-006.jpg" },
  { src: "/media/graphic_design/magazine/page-007.jpg" },
  { src: "/media/graphic_design/magazine/page-008.jpg" },
  { src: "/media/graphic_design/magazine/page-009.jpg" },
  { src: "/media/graphic_design/magazine/page-010.jpg" },
  { src: "/media/graphic_design/magazine/page-011.jpg" },
  { src: "/media/graphic_design/magazine/page-012.jpg" },
  { src: "/media/graphic_design/magazine/page-013.jpg" },
  { src: "/media/graphic_design/magazine/page-014.jpg" },
  { src: "/media/graphic_design/magazine/page-015.jpg" },
  { src: "/media/graphic_design/magazine/page-016.jpg" },
  { src: "/media/graphic_design/magazine/page-017.jpg" },
  { src: "/media/graphic_design/magazine/page-018.jpg" },
  { src: "/media/graphic_design/magazine/page-019.jpg" }
  ] as FlipPage[],
};
