/* eslint-disable */
// AUTO-GENERATED by scripts/gen-galleries.cjs — DO NOT EDIT BY HAND.
// Run `node scripts/gen-galleries.cjs` after changing media.
import type { StaticImageData } from "next/image";
import g0 from "@/components/images/fotos/IMG_0457.jpg";
import g1 from "@/components/images/fotos/IMG_0497.jpg";
import g2 from "@/components/images/fotos/IMG_0534.jpg";
import g3 from "@/components/images/fotos/IMG_0552.jpg";
import g4 from "@/components/images/fotos/IMG_0580.jpg";
import g5 from "@/components/images/fotos/IMG_0585.jpg";
import g6 from "@/components/images/fotos/IMG_0590.jpg";
import g7 from "@/components/images/fotos/IMG_1685.jpg";
import g8 from "@/components/images/fotos/IMG_1686.jpg";
import g9 from "@/components/images/fotos/IMG_1698.jpg";
import g10 from "@/components/images/fotos/IMG_4529.jpg";
import g11 from "@/components/images/fotos/IMG_4571.jpg";
import g12 from "@/components/images/fotos/IMG_4665.jpg";
import g13 from "@/components/images/fotos/IMG_4726.jpg";
import g14 from "@/components/images/fotos/IMG_5212.jpg";
import g15 from "@/components/images/fotos/IMG_6834-2.jpg";
import g16 from "@/components/images/fotos/IMG_6910.jpg";
import g17 from "@/components/images/fotos/IMG_8988.jpg";
import g18 from "@/components/images/fotos/Events/Desfilades/IMG_6963.jpg";
import g19 from "@/components/images/fotos/Events/Desfilades/IMG_7032-Enhanced-NR.jpg";
import g20 from "@/components/images/fotos/Events/Desfilades/IMG_7047.jpg";
import g21 from "@/components/images/fotos/Events/Desfilades/IMG_7062.jpg";
import g22 from "@/components/images/fotos/Events/Desfilades/IMG_7063.jpg";
import g23 from "@/components/images/fotos/Events/Desfilades/IMG_7064.jpg";
import g24 from "@/components/images/fotos/Events/Desfilades/IMG_7079.jpg";
import g25 from "@/components/images/fotos/Events/Desfilades/IMG_7086.jpg";
import g26 from "@/components/images/fotos/Events/Desfilades/IMG_7108.jpg";
import g27 from "@/components/images/fotos/Events/Desfilades/IMG_7124.jpg";
import g28 from "@/components/images/fotos/Negocis/Farmacia/IMG_0006.jpg";
import g29 from "@/components/images/fotos/Negocis/Farmacia/IMG_0100.jpg";
import g30 from "@/components/images/fotos/Negocis/Farmacia/IMG_9637.jpg";
import g31 from "@/components/images/fotos/Negocis/Farmacia/IMG_9677.jpg";
import g32 from "@/components/images/fotos/Negocis/Farmacia/IMG_9712.jpg";
import g33 from "@/components/images/fotos/Negocis/Farmacia/IMG_9742.jpg";
import g34 from "@/components/images/fotos/Negocis/Farmacia/IMG_9804.jpg";
import g35 from "@/components/images/fotos/Negocis/Farmacia/IMG_9837.jpg";
import g36 from "@/components/images/fotos/Retrats/IMG_4804.jpg";
import g37 from "@/components/images/fotos/Retrats/IMG_4868.jpg";
import g38 from "@/components/images/fotos/Retrats/IMG_4879.jpg";
import g39 from "@/components/images/fotos/Retrats/IMG_4887.jpg";
import g40 from "@/components/images/fotos/Retrats/IMG_4933.jpg";
import g41 from "@/components/images/fotos/Retrats/IMG_4976.jpg";
import g42 from "@/components/images/fotos/Retrats/IMG_5074.jpg";
import g43 from "@/components/images/fotos/Retrats/IMG_5169-2.jpg";
import g44 from "@/components/images/fotos/Retrats/IMG_5185.jpg";
import g45 from "@/components/images/fotos/Retrats/IMG_5193.jpg";
import g46 from "@/components/images/fotos/Retrats/IMG_5199.jpg";
import g47 from "@/components/images/fotos/Retrats/IMG_5943.jpg";
import g48 from "@/components/images/fotos/Retrats/IMG_5965.jpg";
import g49 from "@/components/images/fotos/Retrats/IMG_6511.jpg";
import g50 from "@/components/images/fotos/Retrats/IMG_6778.jpg";
import g51 from "@/components/images/fotos/Retrats/IMG_6801.jpg";
import g52 from "@/components/images/fotos/Retrats/IMG_6813.jpg";
import g53 from "@/components/images/fotos/Retrats/IMG_6819.jpg";
import g54 from "@/components/images/fotos/Retrats/IMG_8141.jpg";
import g55 from "@/components/images/fotos/Retrats/IMG_8150.jpg";
import g56 from "@/components/images/fotos/Retrats/IMG_8167.jpg";
import g57 from "@/components/images/fotos/Retrats/IMG_8181.jpg";
import g58 from "@/components/images/fotos/Retrats/IMG_8190.jpg";
import g59 from "@/components/images/fotos/Retrats/IMG_8226.jpg";
import g60 from "@/components/images/fotos/Retrats/IMG_9493.jpg";
import g61 from "@/components/images/fotos/Retrats/IMG_9578.jpg";
import g62 from "@/components/images/fotos/Retrats/IMG_9586.jpg";
import g63 from "@/components/images/fotos/Wedding/IMG_7649.jpg";
import g64 from "@/components/images/fotos/Wedding/IMG_7741.jpg";
import g65 from "@/components/images/fotos/Wedding/IMG_7766.jpg";
import g66 from "@/components/images/fotos/Wedding/IMG_7773.jpg";
import g67 from "@/components/images/fotos/Wedding/IMG_7791.jpg";
import g68 from "@/components/images/fotos/Wedding/IMG_7795.jpg";
import g69 from "@/components/images/fotos/Wedding/IMG_7808.jpg";
import g70 from "@/components/images/fotos/Wedding/IMG_7813.jpg";
import g71 from "@/components/images/fotos/Wedding/IMG_7819.jpg";
import g72 from "@/components/images/fotos/Wedding/IMG_7824.jpg";
import g73 from "@/components/images/fotos/Wedding/IMG_7830.jpg";
import g74 from "@/components/images/fotos/Wedding/IMG_7851.jpg";
import g75 from "@/components/images/fotos/Wedding/IMG_7857.jpg";
import g76 from "@/components/images/fotos/Wedding/IMG_7888.jpg";
import g77 from "@/components/images/graphic_design/Cartell_Informatiu.png";
import g78 from "@/components/images/graphic_design/Lettering.png";
import g79 from "@/components/images/graphic_design/Lowlight.png";
import g80 from "@/components/images/graphic_design/Pancarta.png";
import g81 from "@/components/images/graphic_design/RollUp.png";
import g82 from "@/components/images/graphic_design/WaterReflection.png";
import g83 from "@/components/images/graphic_design/pride26.png";
import g84 from "@/components/images/graphic_design/samarreta.png";

export interface GalleryImage { kind: "image"; src: StaticImageData; name: string; }
export interface GalleryVideo { kind: "video"; src: string; poster?: string; name: string; }
export type GalleryMedia = GalleryImage | GalleryVideo;
export interface GalleryGroup { name: string; path: string[]; items: GalleryMedia[]; }
export interface SectionGallery { folder: string; rootItems: GalleryMedia[]; groups: GalleryGroup[]; }

export const galleries: Record<string, SectionGallery> = {
  "3d": {
    folder: "3d",
    rootItems: [{ kind: "video", src: "/media/3d/2RogerTorresAnimadcioDeLinea3DII.mp4", poster: "/media/3d/2RogerTorresAnimadcioDeLinea3DII.poster.jpg", name: "2RogerTorresAnimadcióDeLinea3DII" }, { kind: "video", src: "/media/3d/PlasmaBall_Roger_Torres_Linares.mp4", poster: "/media/3d/PlasmaBall_Roger_Torres_Linares.poster.jpg", name: "PlasmaBall_Roger_Torres_Linares" }, { kind: "video", src: "/media/3d/VFX.mp4", poster: "/media/3d/VFX.poster.jpg", name: "VFX" }],
    groups: [
    ],
  },
  "web": {
    folder: "Web",
    rootItems: [{ kind: "video", src: "/media/Web/web-lgtbicostabrava.mp4", poster: "/media/Web/web-lgtbicostabrava.poster.jpg", name: "web-lgtbicostabrava" }],
    groups: [
    ],
  },
  "foto": {
    folder: "fotos",
    rootItems: [{ kind: "image", src: g0, name: "IMG_0457" }, { kind: "image", src: g1, name: "IMG_0497" }, { kind: "image", src: g2, name: "IMG_0534" }, { kind: "image", src: g3, name: "IMG_0552" }, { kind: "image", src: g4, name: "IMG_0580" }, { kind: "image", src: g5, name: "IMG_0585" }, { kind: "image", src: g6, name: "IMG_0590" }, { kind: "image", src: g7, name: "IMG_1685" }, { kind: "image", src: g8, name: "IMG_1686" }, { kind: "image", src: g9, name: "IMG_1698" }, { kind: "image", src: g10, name: "IMG_4529" }, { kind: "image", src: g11, name: "IMG_4571" }, { kind: "image", src: g12, name: "IMG_4665" }, { kind: "image", src: g13, name: "IMG_4726" }, { kind: "image", src: g14, name: "IMG_5212" }, { kind: "image", src: g15, name: "IMG_6834-2" }, { kind: "image", src: g16, name: "IMG_6910" }, { kind: "image", src: g17, name: "IMG_8988" }],
    groups: [
      { name: "Desfilades", path: ["Events","Desfilades"], items: [{ kind: "image", src: g18, name: "IMG_6963" }, { kind: "image", src: g19, name: "IMG_7032-Enhanced-NR" }, { kind: "image", src: g20, name: "IMG_7047" }, { kind: "image", src: g21, name: "IMG_7062" }, { kind: "image", src: g22, name: "IMG_7063" }, { kind: "image", src: g23, name: "IMG_7064" }, { kind: "image", src: g24, name: "IMG_7079" }, { kind: "image", src: g25, name: "IMG_7086" }, { kind: "image", src: g26, name: "IMG_7108" }, { kind: "image", src: g27, name: "IMG_7124" }] },
      { name: "Farmacia", path: ["Negocis","Farmacia"], items: [{ kind: "image", src: g28, name: "IMG_0006" }, { kind: "image", src: g29, name: "IMG_0100" }, { kind: "image", src: g30, name: "IMG_9637" }, { kind: "image", src: g31, name: "IMG_9677" }, { kind: "image", src: g32, name: "IMG_9712" }, { kind: "image", src: g33, name: "IMG_9742" }, { kind: "image", src: g34, name: "IMG_9804" }, { kind: "image", src: g35, name: "IMG_9837" }] },
      { name: "Retrats", path: ["Retrats"], items: [{ kind: "image", src: g36, name: "IMG_4804" }, { kind: "image", src: g37, name: "IMG_4868" }, { kind: "image", src: g38, name: "IMG_4879" }, { kind: "image", src: g39, name: "IMG_4887" }, { kind: "image", src: g40, name: "IMG_4933" }, { kind: "image", src: g41, name: "IMG_4976" }, { kind: "image", src: g42, name: "IMG_5074" }, { kind: "image", src: g43, name: "IMG_5169-2" }, { kind: "image", src: g44, name: "IMG_5185" }, { kind: "image", src: g45, name: "IMG_5193" }, { kind: "image", src: g46, name: "IMG_5199" }, { kind: "image", src: g47, name: "IMG_5943" }, { kind: "image", src: g48, name: "IMG_5965" }, { kind: "image", src: g49, name: "IMG_6511" }, { kind: "image", src: g50, name: "IMG_6778" }, { kind: "image", src: g51, name: "IMG_6801" }, { kind: "image", src: g52, name: "IMG_6813" }, { kind: "image", src: g53, name: "IMG_6819" }, { kind: "image", src: g54, name: "IMG_8141" }, { kind: "image", src: g55, name: "IMG_8150" }, { kind: "image", src: g56, name: "IMG_8167" }, { kind: "image", src: g57, name: "IMG_8181" }, { kind: "image", src: g58, name: "IMG_8190" }, { kind: "image", src: g59, name: "IMG_8226" }, { kind: "image", src: g60, name: "IMG_9493" }, { kind: "image", src: g61, name: "IMG_9578" }, { kind: "image", src: g62, name: "IMG_9586" }] },
      { name: "Wedding", path: ["Wedding"], items: [{ kind: "image", src: g63, name: "IMG_7649" }, { kind: "image", src: g64, name: "IMG_7741" }, { kind: "image", src: g65, name: "IMG_7766" }, { kind: "image", src: g66, name: "IMG_7773" }, { kind: "image", src: g67, name: "IMG_7791" }, { kind: "image", src: g68, name: "IMG_7795" }, { kind: "image", src: g69, name: "IMG_7808" }, { kind: "image", src: g70, name: "IMG_7813" }, { kind: "image", src: g71, name: "IMG_7819" }, { kind: "image", src: g72, name: "IMG_7824" }, { kind: "image", src: g73, name: "IMG_7830" }, { kind: "image", src: g74, name: "IMG_7851" }, { kind: "image", src: g75, name: "IMG_7857" }, { kind: "image", src: g76, name: "IMG_7888" }] },
    ],
  },
  "disseny": {
    folder: "graphic_design",
    rootItems: [{ kind: "image", src: g77, name: "Cartell_Informatiu" }, { kind: "image", src: g78, name: "Lettering" }, { kind: "image", src: g79, name: "Lowlight" }, { kind: "video", src: "/media/graphic_design/MotionGraphic.mp4", poster: "/media/graphic_design/MotionGraphic.poster.jpg", name: "MotionGraphic" }, { kind: "video", src: "/media/graphic_design/Motion_Graphics2.mp4", poster: "/media/graphic_design/Motion_Graphics2.poster.jpg", name: "Motion_Graphics2" }, { kind: "image", src: g80, name: "Pancarta" }, { kind: "image", src: g81, name: "RollUp" }, { kind: "image", src: g82, name: "WaterReflection" }, { kind: "image", src: g83, name: "pride26" }, { kind: "image", src: g84, name: "samarreta" }],
    groups: [
    ],
  },
};
