/* eslint-disable */
// AUTO-GENERATED by scripts/gen-galleries.cjs — DO NOT EDIT BY HAND.
// Landscape loose photos from components/images/fotos for the home "visual selection".
import type { StaticImageData } from "next/image";
import v0 from "@/components/images/fotos/IMG_0590.jpg";
import v1 from "@/components/images/fotos/IMG_4665.jpg";
import v2 from "@/components/images/fotos/IMG_4726.jpg";
import v3 from "@/components/images/fotos/IMG_5212.jpg";
import v4 from "@/components/images/fotos/IMG_6834-2.jpg";

export interface VisualSelectionImage { src: StaticImageData; name: string; }
export const visualSelection: VisualSelectionImage[] = [
  { src: v0, name: "IMG_0590" },
  { src: v1, name: "IMG_4665" },
  { src: v2, name: "IMG_4726" },
  { src: v3, name: "IMG_5212" },
  { src: v4, name: "IMG_6834-2" }
];
